### ISSUE TITLE
Audio Not Working

### ISSUE THREAD

**Issue by waseemm1975** [unchatbar/unchatbar#7]

**Comment by gernsdorfer** [comment]
Can you give me more information to this problem. 
* what Browser/Plattform did you use ?
* are there any error messages in the console of your browser
* did you make a call behind a firewall or a NAT 

For last Point I've just changed the socket/Xhr Connection to ssl, maybe that helps.

**Comment by waseemm1975** [comment]
yea got thanks, awesome project bro. 
I noticed a small bug... when user A is calling user B but user A hangs up the call keeps going into user B
may you please also shoot me an email waseemm1975@gmail.com
thanks man

**Comment by gernsdorfer** [comment]
i fixed this bug. now the app handle the close event correctly. The firefox support for "onClose" event is still buggy in this browser.
Here are the open issues to the "onClose" event for Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=881337
https://bugzilla.mozilla.org/show_bug.cgi?id=1009124
